/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GudngvfA4QD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import React from 'react';
import { Button } from "./button"
import { Badge } from "./badge"
import { Avatar, AvatarImage, AvatarFallback } from "./avatar"
import { Textarea } from "./textarea"
import { Bot } from "lucide-react"

export function ChatUIComponent() {
  return (
    <div className="flex flex-col h-screen w-full">
      <div className="flex h-full">
        <div className="flex flex-col gap-4 border-r p-4 md:p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <BotIcon className="h-6 w-6" />
              <span className="font-medium">Task Library</span>
            </div>
            <Button variant="ghost" size="icon">
              <PlusIcon className="h-5 w-5" />
              <span className="sr-only">New Task</span>
            </Button>
          </div>
          <div className="flex items-center gap-2 rounded-md bg-muted px-3 py-2">
            <SearchIcon className="h-4 w-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="Search tasks..."
              className="w-full bg-transparent text-sm focus:outline-none"
            />
          </div>
          <div className="flex-1 overflow-auto">
            <div className="space-y-2">
              <div className="flex items-center justify-between rounded-md bg-muted px-3 py-2">
                <div className="flex items-center gap-2">
                  <ListIcon className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm">Completed Tasks</span>
                </div>
                <Badge className="bg-primary text-primary-foreground">12</Badge>
              </div>
              <div className="flex items-center justify-between rounded-md bg-muted px-3 py-2">
                <div className="flex items-center gap-2">
                  <CalendarIcon className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm">Upcoming Tasks</span>
                </div>
                <Badge className="bg-primary text-primary-foreground">5</Badge>
              </div>
              <div className="flex items-center justify-between rounded-md bg-muted px-3 py-2">
                <div className="flex items-center gap-2">
                  <ClockIcon className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm">Overdue Tasks</span>
                </div>
                <Badge className="bg-primary text-primary-foreground">3</Badge>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2 rounded-md bg-muted px-3 py-2">
            <UserIcon className="h-4 w-4 text-muted-foreground" />
            <span className="text-sm">Account Settings</span>
          </div>
        </div>
        <div className="flex-1 overflow-auto border-b">
          <div className="flex flex-col gap-4 p-4 md:p-6">
            <div className="flex items-start gap-4">
              <Avatar className="h-8 w-8 border">
                <AvatarImage src="/placeholder-user.jpg" alt="User" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-medium">You</div>
                <div className="rounded-md bg-muted p-3 text-sm">
                  <p>Hi there! Im looking for help with a code generation task. Can you assist me?</p>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="h-8 w-8 border">
                <AvatarImage src="/placeholder-user.jpg" alt="User" />
                <AvatarFallback>AI</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-medium">AI Assistant</div>
                <div className="rounded-md bg-primary p-3 text-sm text-primary-foreground">
                  <p>
                    Absolutely! I would be happy to help with your code generation task. What kind of code are you looking
                    to generate?
                  </p>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="h-8 w-8 border">
                <AvatarImage src="/placeholder-user.jpg" alt="User" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-medium">You</div>
                <div className="rounded-md bg-muted p-3 text-sm">
                  <p>
                    I need to generate a simple React component that displays a list of items with some basic styling.
                  </p>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="h-8 w-8 border">
                <AvatarImage src="/placeholder-user.jpg" alt="User" />
                <AvatarFallback>AI</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-medium">AI Assistant</div>
                <div className="rounded-md bg-primary p-3 text-sm text-primary-foreground">
                  <p>Okay, let me generate a simple React component for you:</p>
                  <pre className="mt-2 bg-primary-foreground/10 p-2 text-xs text-primary-foreground">{`function ItemList() {
  const items = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];

  return (
    <div className="space-y-2">
      {items.map((item, index) => (
        <div
          key={index}
          className="rounded-md bg-muted p-3 text-sm text-muted-foreground"
        >
          {item}
        </div>
      ))}
    </div>
  );
}`}</pre>
                  <p className="mt-2">
                    This component renders a list of items with a simple rounded-corner card style. Let me know if you
                    need any modifications or have additional requirements.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex items-center gap-2 border-t p-4 md:p-6">
        <Textarea
          placeholder="Type your message..."
          className="flex-1 resize-none rounded-md border border-neutral-400 px-4 py-2 text-sm focus:border-primary focus:outline-none"
          rows={1}
        />
        <Button className="rounded-md px-4 py-2 text-sm">Send</Button>
      </div>
    </div>
  )
}

function BotIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function CalendarIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClockIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function ListIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}


function PlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UserIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )

  

}
